### ISSUE TITLE
npm test failing

### ISSUE THREAD

**Issue by pranavburnwal** [OpenCerts/open-certificate#19]
npm run test is failing on MacOS

<path> -> Absolute path of current directory
<user> -> username

Output:

```
➜  open-certificate$ npm run test

> @govtechsg/open-certificate@1.1.38 test <path>/opencert/node_modules/@govtechsg/open-certificate
> npm run build && nyc --reporter=html mocha --timeout 5000 -- ./test/helpers.js './schema/**/*.test.js' './src/**/*.test.js' './test/**/*.test.js'


> @govtechsg/open-certificate@1.1.38 build <path>/opencert/node_modules/@govtechsg/open-certificate
> npm run clean && rollup -c


> @govtechsg/open-certificate@1.1.38 clean <path>/opencert/node_modules/@govtechsg/open-certificate
> rm -rf dist/

sh: rollup: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @govtechsg/open-certificate@1.1.38 build: `npm run clean && rollup -c`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @govtechsg/open-certificate@1.1.38 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<user>/.npm/_logs/2019-05-12T15_43_35_851Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @govtechsg/open-certificate@1.1.38 test: `npm run build && nyc --reporter=html mocha --timeout 5000 -- ./test/helpers.js './schema/**/*.test.js' './src/**/*.test.js' './test/**/*.test.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @govtechsg/open-certificate@1.1.38 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<user>/.npm/_logs/2019-05-12T15_43_35_882Z-debug.log

```

DEBUG Log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@6.9.0
3 info using node@v10.13.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle @govtechsg/open-certificate@1.1.38~pretest: @govtechsg/open-certificate@1.1.38
6 info lifecycle @govtechsg/open-certificate@1.1.38~test: @govtechsg/open-certificate@1.1.38
7 verbose lifecycle @govtechsg/open-certificate@1.1.38~test: unsafe-perm in lifecycle true
8 verbose lifecycle @govtechsg/open-certificate@1.1.38~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:<PATH>/opencert/node_modules/@govtechsg/open-certificate/node_modules/.bin:<PATH>/opencert/node_modules/.bin:/Users/<user>/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @govtechsg/open-certificate@1.1.38~test: CWD: <path>/opencert/node_modules/@govtechsg/open-certificate
10 silly lifecycle @govtechsg/open-certificate@1.1.38~test: Args: [ '-c',
10 silly lifecycle   'npm run build && nyc --reporter=html mocha --timeout 5000 -- ./test/helpers.js \'./schema/**/*.test.js\' \'./src/**/*.test.js\' \'./test/**/*.test.js\'' ]
11 silly lifecycle @govtechsg/open-certificate@1.1.38~test: Returned: code: 1  signal: null
12 info lifecycle @govtechsg/open-certificate@1.1.38~test: Failed to exec test script
13 verbose stack Error: @govtechsg/open-certificate@1.1.38 test: `npm run build && nyc --reporter=html mocha --timeout 5000 -- ./test/helpers.js './schema/**/*.test.js' './src/**/*.test.js' './test/**/*.test.js'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @govtechsg/open-certificate@1.1.38
15 verbose cwd <PATH>/opencert/node_modules/@govtechsg/open-certificate
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/Cellar/node/11.2.0/bin/node" "/usr/local/bin/npm" "run" "test"
18 verbose node v10.13.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @govtechsg/open-certificate@1.1.38 test: `npm run build && nyc --reporter=html mocha --timeout 5000 -- ./test/helpers.js './schema/**/*.test.js' './src/**/*.test.js' './test/**/*.test.js'`
22 error Exit status 1
23 error Failed at the @govtechsg/open-certificate@1.1.38 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rjchow** [comment]
we did find an issue on OS X but it wasn't the same error as what you have here - have you ran `npm install`?

**Comment by pranavburnwal** [comment]
Yes, I did.
Also ran npm rebuild.

Doesn't work.

**Comment by pranavburnwal** [comment]
Using ubuntu on Docker. Now working.
Thanks

**Comment by rjchow** [comment]
most likely something's weird with your os x environment, it works fine on 3/3 macs that I've tested on
