### ISSUE TITLE
Unable to issue certificate with Schema 1.5 anymore [Post Schema 2.0 merge]

### ISSUE THREAD

**Issue by pranavburnwal** [OpenCerts/open-certificate#39]
Hi,

the node module is no longer able to issue data which is on older schema. It is by default taking the default schema and not even considering the older data with older schema. This is breaking older code. 

Suggestions?

Error thrown:

```/Users/<user>/Documents/<folder>/test/opencert/node_modules/@govtechsg/open-certificate/node_modules/@govtechsg/open-attestation/dist/cjs/index.js:16
    throw new Error("Invalid document:" + JSON.stringify(data, null, 2));
    ^

Error: Invalid document:{<whole JSON Doc>}
at createDocument (/Users/<user>/Documents/<folder>/test/opencert/node_modules/@govtechsg/open-certificate/node_modules/@govtechsg/open-attestation/dist/cjs/index.js:16:11)
    at exports.issueDocument (/Users/<user>/Documents/<folder>/test/opencert/node_modules/@govtechsg/open-certificate/node_modules/@govtechsg/open-attestation/dist/cjs/index.js:19:20)
    at Object.issueCertificate (/Users/<user>/Documents/<folder>/test/opencert/node_modules/@govtechsg/open-certificate/dist/open-certificate.js:1424:34)
    at Object.<anonymous> (/Users/<user>/Documents/<folder>/test/opencert/app.js:92:30)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Thanks

**Comment by yehjxraymond** [comment]
Hi, thanks for the report, we are currently looking at creating a flag to select older schemas. In the meanwhile could you checkout a version of the CLI that uses an older schema?
